###
 # THIS FILE IS AUTOMATICALLY GENERATED
 # Do not edit this file. It will be overwritten when the configure script is run.
###

######
# Build ID: 677e4a3c47b3472e
# Executable: ./bin/champsim_custom_loop
# Module Names: ('btbDbasic_btb', 'branchDbimodal', 'branchDgshare', 'branchDhashed_perceptron', 'branchDperceptron', 'prefetcherDcustom_pref', 'prefetcherDip_stride', 'prefetcherDnext_line', 'prefetcherDno', 'prefetcherDspp_dev', 'prefetcherDva_ampm_lite', 'replacementDdrrip', 'replacementDlru', 'replacementDrandom', 'replacementDship', 'replacementDsrrip')
######

BIN_ROOT := bin
compile_commands $(BIN_ROOT)/champsim_custom_loop: build_id := \
  677e4a3c47b3472e
nonbase_module_objs += $(filter-out $(base_module_objs),$(call get_module_list, btb/basic_btb \
  branch/bimodal branch/gshare branch/hashed_perceptron \
  branch/perceptron prefetcher/custom_pref prefetcher/ip_stride \
  prefetcher/next_line prefetcher/no prefetcher/spp_dev \
  prefetcher/va_ampm_lite replacement/drrip replacement/lru \
  replacement/random replacement/ship replacement/srrip \
  ))
build_ids += 677e4a3c47b3472e
executable_name += $(BIN_ROOT)/champsim_custom_loop
